language: julia

os:
  - osx

julia:
  - 1.6

branches:
  only:
    - master

notifications:
  email: false

coveralls: true

# jobs:
#   script:
#  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.develop(PackageSpec(path="https://github.com/marteresagh/Common.jl.git")); Pkg.instantiate()'
#  #- julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
